=== mypsycho/NetSend/src/org/mypsycho/netsend/NetSend.dtd
<!ELEMENT NetSend (Key|List)+>
 <!ATTLIST NetSend port CDATA "0">
 <!ATTLIST NetSend name CDATA "">
 <!ATTLIST NetSend expanded (all|true|false) "true">

    <!ELEMENT List (Key|List)+>
     <!ATTLIST List name CDATA #REQUIRED>
     <!ATTLIST List expanded (true|false) "false">

    <!ELEMENT Key EMPTY>
     <!ATTLIST Key name CDATA #REQUIRED>
     <!ATTLIST Key machine CDATA #REQUIRED>
     <!ATTLIST Key port CDATA "0">

=== mypsycho/NetSend/test/NetSend.5001.xml
<?xml version="1.0" ?>
<!DOCTYPE NetSend SYSTEM "NetSend.dtd">
<!-- DO NOT CHANGE DTD REFERENCE -->

<NetSend name="5001_Tester" port="5001" > <!--  -->

        <Key name="test" machine="localhost" />
        <Key name="test 2" machine="localhost" port="6001" />

        <Key name="N1" machine="m1"/>
        <Key name="N2" machine="m2"/>

        <List name="A">
            <Key name="A1" machine="m1"/>
            <Key name="A2" machine="m2"/>
        </List>
        <List name="B">
            <Key name="B1" machine="m1"/>
            <Key name="B2" machine="m2"/>
            <List name="BA" expanded="true" >
                <Key name="BA1" machine="m1"/>
                <Key name="BA2" machine="m2"/>
            </List>
        </List>

        <List name="L1">
            <Key name="N3" machine="m3"/>
            <Key name="N4" machine="m4"/>
            <Key name="N5" machine="m5"/>
        </List>

</NetSend>
